development_task:
  description: >
    Design and implement a project or feature focused on {topic}.
    Use your expertise in {topic} to create scalable, maintainable, and high-performance solutions, adhering to best practices.
  expected_output: >
    - A fully implemented and functional solution, including:
      - A {topic}-based backend or feature.
      - Documentation detailing the architecture, setup, and usage.
      - Test cases to validate the functionality and ensure code quality.
  agent: developer

debugging_task:
  description: >
    Identify and fix issues in a project related to {topic}.
    Debug {topic}-based backend services and ensure optimal performance, reliability, and correctness.
  expected_output: >
    - A detailed summary of the identified issues and their root causes.
    - Updated and error-free Python code.
    - Verification logs or test cases confirming that the issues are resolved.
  agent: developer
